/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Alignment = { 'center' : null } |
  { 'left' : null } |
  { 'right' : null };
export interface HeroContent {
  'sectionBody' : string,
  'sectionTitle' : string,
  'bodyPosition' : Position,
  'imageSrc' : string,
  'imagePosition' : Position,
  'titlePosition' : Position,
}
export interface Position {
  'horizontal' : Alignment,
  'vertical' : { 'top' : null } |
    { 'middle' : null } |
    { 'bottom' : null },
}
export interface Section { 'sectionBody' : string, 'sectionTitle' : string }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WebsiteContent {
  'siteTitle' : string,
  'heroSection' : HeroContent,
  'footerText' : string,
  'mainSection' : Section,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWebsiteContent' : ActorMethod<[], WebsiteContent>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateWebsiteContent' : ActorMethod<[WebsiteContent], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];