/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Alignment = IDL.Variant({
  'center' : IDL.Null,
  'left' : IDL.Null,
  'right' : IDL.Null,
});
export const Position = IDL.Record({
  'horizontal' : Alignment,
  'vertical' : IDL.Variant({
    'top' : IDL.Null,
    'middle' : IDL.Null,
    'bottom' : IDL.Null,
  }),
});
export const HeroContent = IDL.Record({
  'sectionBody' : IDL.Text,
  'sectionTitle' : IDL.Text,
  'bodyPosition' : Position,
  'imageSrc' : IDL.Text,
  'imagePosition' : Position,
  'titlePosition' : Position,
});
export const Section = IDL.Record({
  'sectionBody' : IDL.Text,
  'sectionTitle' : IDL.Text,
});
export const WebsiteContent = IDL.Record({
  'siteTitle' : IDL.Text,
  'heroSection' : HeroContent,
  'footerText' : IDL.Text,
  'mainSection' : Section,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWebsiteContent' : IDL.Func([], [WebsiteContent], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateWebsiteContent' : IDL.Func([WebsiteContent], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Alignment = IDL.Variant({
    'center' : IDL.Null,
    'left' : IDL.Null,
    'right' : IDL.Null,
  });
  const Position = IDL.Record({
    'horizontal' : Alignment,
    'vertical' : IDL.Variant({
      'top' : IDL.Null,
      'middle' : IDL.Null,
      'bottom' : IDL.Null,
    }),
  });
  const HeroContent = IDL.Record({
    'sectionBody' : IDL.Text,
    'sectionTitle' : IDL.Text,
    'bodyPosition' : Position,
    'imageSrc' : IDL.Text,
    'imagePosition' : Position,
    'titlePosition' : Position,
  });
  const Section = IDL.Record({
    'sectionBody' : IDL.Text,
    'sectionTitle' : IDL.Text,
  });
  const WebsiteContent = IDL.Record({
    'siteTitle' : IDL.Text,
    'heroSection' : HeroContent,
    'footerText' : IDL.Text,
    'mainSection' : Section,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWebsiteContent' : IDL.Func([], [WebsiteContent], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateWebsiteContent' : IDL.Func([WebsiteContent], [], []),
  });
};

export const init = ({ IDL }) => { return []; };