/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Position {
    horizontal: Alignment;
    vertical: Variant_top_middle_bottom;
}
export interface HeroContent {
    sectionBody: string;
    sectionTitle: string;
    bodyPosition: Position;
    imageSrc: string;
    imagePosition: Position;
    titlePosition: Position;
}
export interface Section {
    sectionBody: string;
    sectionTitle: string;
}
export interface WebsiteContent {
    siteTitle: string;
    heroSection: HeroContent;
    footerText: string;
    mainSection: Section;
}
export interface UserProfile {
    name: string;
}
export enum Alignment {
    center = "center",
    left = "left",
    right = "right"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_top_middle_bottom {
    top = "top",
    middle = "middle",
    bottom = "bottom"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDraftContent(): Promise<WebsiteContent>;
    getLiveContent(): Promise<WebsiteContent>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    publishDraft(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateDraftContent(newContent: WebsiteContent): Promise<void>;
}
import type { Alignment as _Alignment, HeroContent as _HeroContent, Position as _Position, Section as _Section, UserProfile as _UserProfile, UserRole as _UserRole, WebsiteContent as _WebsiteContent } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDraftContent(): Promise<WebsiteContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getDraftContent();
                return from_candid_WebsiteContent_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDraftContent();
            return from_candid_WebsiteContent_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLiveContent(): Promise<WebsiteContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getLiveContent();
                return from_candid_WebsiteContent_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLiveContent();
            return from_candid_WebsiteContent_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async publishDraft(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishDraft();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishDraft();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateDraftContent(arg0: WebsiteContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDraftContent(to_candid_WebsiteContent_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDraftContent(to_candid_WebsiteContent_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Alignment_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Alignment): Alignment {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_HeroContent_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HeroContent): HeroContent {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Position_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Position): Position {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_WebsiteContent_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WebsiteContent): WebsiteContent {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    horizontal: _Alignment;
    vertical: {
        top: null;
    } | {
        middle: null;
    } | {
        bottom: null;
    };
}): {
    horizontal: Alignment;
    vertical: Variant_top_middle_bottom;
} {
    return {
        horizontal: from_candid_Alignment_n12(_uploadFile, _downloadFile, value.horizontal),
        vertical: from_candid_variant_n14(_uploadFile, _downloadFile, value.vertical)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    siteTitle: string;
    heroSection: _HeroContent;
    footerText: string;
    mainSection: _Section;
}): {
    siteTitle: string;
    heroSection: HeroContent;
    footerText: string;
    mainSection: Section;
} {
    return {
        siteTitle: value.siteTitle,
        heroSection: from_candid_HeroContent_n8(_uploadFile, _downloadFile, value.heroSection),
        footerText: value.footerText,
        mainSection: value.mainSection
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sectionBody: string;
    sectionTitle: string;
    bodyPosition: _Position;
    imageSrc: string;
    imagePosition: _Position;
    titlePosition: _Position;
}): {
    sectionBody: string;
    sectionTitle: string;
    bodyPosition: Position;
    imageSrc: string;
    imagePosition: Position;
    titlePosition: Position;
} {
    return {
        sectionBody: value.sectionBody,
        sectionTitle: value.sectionTitle,
        bodyPosition: from_candid_Position_n10(_uploadFile, _downloadFile, value.bodyPosition),
        imageSrc: value.imageSrc,
        imagePosition: from_candid_Position_n10(_uploadFile, _downloadFile, value.imagePosition),
        titlePosition: from_candid_Position_n10(_uploadFile, _downloadFile, value.titlePosition)
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    center: null;
} | {
    left: null;
} | {
    right: null;
}): Alignment {
    return "center" in value ? Alignment.center : "left" in value ? Alignment.left : "right" in value ? Alignment.right : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    top: null;
} | {
    middle: null;
} | {
    bottom: null;
}): Variant_top_middle_bottom {
    return "top" in value ? Variant_top_middle_bottom.top : "middle" in value ? Variant_top_middle_bottom.middle : "bottom" in value ? Variant_top_middle_bottom.bottom : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_Alignment_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Alignment): _Alignment {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_HeroContent_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HeroContent): _HeroContent {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_Position_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Position): _Position {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_WebsiteContent_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WebsiteContent): _WebsiteContent {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    siteTitle: string;
    heroSection: HeroContent;
    footerText: string;
    mainSection: Section;
}): {
    siteTitle: string;
    heroSection: _HeroContent;
    footerText: string;
    mainSection: _Section;
} {
    return {
        siteTitle: value.siteTitle,
        heroSection: to_candid_HeroContent_n17(_uploadFile, _downloadFile, value.heroSection),
        footerText: value.footerText,
        mainSection: value.mainSection
    };
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sectionBody: string;
    sectionTitle: string;
    bodyPosition: Position;
    imageSrc: string;
    imagePosition: Position;
    titlePosition: Position;
}): {
    sectionBody: string;
    sectionTitle: string;
    bodyPosition: _Position;
    imageSrc: string;
    imagePosition: _Position;
    titlePosition: _Position;
} {
    return {
        sectionBody: value.sectionBody,
        sectionTitle: value.sectionTitle,
        bodyPosition: to_candid_Position_n19(_uploadFile, _downloadFile, value.bodyPosition),
        imageSrc: value.imageSrc,
        imagePosition: to_candid_Position_n19(_uploadFile, _downloadFile, value.imagePosition),
        titlePosition: to_candid_Position_n19(_uploadFile, _downloadFile, value.titlePosition)
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    horizontal: Alignment;
    vertical: Variant_top_middle_bottom;
}): {
    horizontal: _Alignment;
    vertical: {
        top: null;
    } | {
        middle: null;
    } | {
        bottom: null;
    };
} {
    return {
        horizontal: to_candid_Alignment_n21(_uploadFile, _downloadFile, value.horizontal),
        vertical: to_candid_variant_n23(_uploadFile, _downloadFile, value.vertical)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Alignment): {
    center: null;
} | {
    left: null;
} | {
    right: null;
} {
    return value == Alignment.center ? {
        center: null
    } : value == Alignment.left ? {
        left: null
    } : value == Alignment.right ? {
        right: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_top_middle_bottom): {
    top: null;
} | {
    middle: null;
} | {
    bottom: null;
} {
    return value == Variant_top_middle_bottom.top ? {
        top: null
    } : value == Variant_top_middle_bottom.middle ? {
        middle: null
    } : value == Variant_top_middle_bottom.bottom ? {
        bottom: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
